In [13]:
# import pandas as pd
#
# def clean_duplicates(df: pd.DataFrame, label_col_list: list) -> pd.DataFrame:
#     """
#     清理重复行，保留每组重复行的第一行，并计算其他行的平均值。
#
#     :param df: 输入的DataFrame
#     :param label_col_list: 用于分组的列名列表
#     :return: 清理后的DataFrame
#     """
#
#     agg_dict = {col: 'mean' for col in label_col_list}
#     cols_list = list(df.columns.difference(label_col_list))
#     df_merged = (
#         df
#         .groupby(cols_list, dropna=False, sort=False)  # 若有缺失值也能一起分组
#         .agg(agg_dict)
#         .reset_index()
#     )
#
#     return df_merged
#
# def combine_dataframes(df1: pd.DataFrame, df2: pd.DataFrame) -> pd.DataFrame:
#     """
#     合并两个DataFrame，保留所有样本。
#
#     :param df1: 第一个DataFrame
#     :param df2: 第二个DataFrame
#     :param on: 用于合并的列名列表
#     :param how: 合并方式，默认为'outer'
#     :return: 合并后的DataFrame
#     """
#     cols_list = list(df1.columns.intersection(df2.columns))
#     df_final = pd.merge(
#         df1,
#         df2,
#         on=cols_list,
#         how='outer',          # outer → 保留所有样本
#     )
#     return df_final
#
# tasks_names = [
#     'Flowability',
#     'Porosity',
#     'Compressive strength',
#     'Flexural strength'
# ]

In [14]:
# df_fs = pd.read_excel('UHPC_original.xlsx', sheet_name=tasks_names[-1]).astype(float)
# df_cs = pd.read_excel('UHPC_original.xlsx', sheet_name=tasks_names[-2]).astype(float)
# df_p = pd.read_excel('UHPC_original.xlsx', sheet_name=tasks_names[-3]).astype(float)
# df_f = pd.read_excel('UHPC_original.xlsx', sheet_name=tasks_names[-4]).astype(float)
#
#
# df_fs_cleaned = clean_duplicates(df_fs, [tasks_names[-1]])
# df_cs_cleaned = clean_duplicates(df_cs, [tasks_names[-2]])
# df_p_cleaned = clean_duplicates(df_p, [tasks_names[-3]])
# df_f_cleaned = clean_duplicates(df_f, [tasks_names[-4]])
#
# df_final = combine_dataframes(df_f_cleaned, df_p_cleaned)
# df_final = combine_dataframes(df_final, df_cs_cleaned)
# df_final = combine_dataframes(df_final, df_fs_cleaned)

In [15]:
df_final

,1,2,3,4,5,6,7,8,9,10,...,19,20,21,Flowability,22,Porosity,23,24,Compressive strength,Flexural strength
0,582.1,52.5,1.0,0.0,259.9,0.0,0.0,24.3,0.0,1256.1,...,0.0,0.0,0.0,6.288737,28.0,12.88,40.0,160.0,100.07,12.752294
1,582.1,52.5,1.0,0.0,259.9,0.0,0.0,24.3,0.0,1256.1,...,0.0,0.0,0.0,6.288737,91.0,11.75,40.0,160.0,108.78,14.220183
2,591.9,52.5,1.0,0.0,264.3,0.0,0.0,24.7,0.0,1277.2,...,0.0,0.0,0.0,8.947639,28.0,12.06,40.0,160.0,105.43,14.495413
3,591.9,52.5,1.0,0.0,264.3,0.0,0.0,24.7,0.0,1277.2,...,0.0,0.0,0.0,8.947639,91.0,10.48,40.0,160.0,116.07,16.467890
4,600.0,52.5,1.0,0.0,267.9,0.0,0.0,25.0,0.0,1294.6,...,0.0,0.0,0.0,11.264783,28.0,12.29,40.0,160.0,103.79,14.174312
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
788,475.0,42.5,1.0,1.0,0.0,317.0,264.0,0.0,0.0,1056.0,...,2.0,0.2,13.0,NaN,91.0,NaN,40.0,160.0,NaN,41.496909
789,317.0,42.5,1.0,1.0,0.0,475.0,264.0,0.0,0.0,1056.0,...,2.0,0.2,13.0,NaN,91.0,NaN,40.0,160.0,NaN,34.259079
790,634.0,42.5,1.0,1.0,159.0,0.0,264.0,0.0,0.0,1056.0,...,2.0,0.2,13.0,NaN,91.0,NaN,40.0,160.0,NaN,38.504096
791,475.0,42.5,1.0,1.0,317.0,0.0,264.0,0.0,0.0,1056.0,...,2.0,0.2,13.0,NaN,91.0,NaN,40.0,160.0,NaN,34.714269
792,317.0,42.5,1.0,1.0,475.0,0.0,264.0,0.0,0.0,1056.0,...,2.0,0.2,13.0,NaN,91.0,NaN,40.0,160.0,NaN,32.354542

In [16]:
# df_final_reduction = df_final.dropna(subset=['Flowability'])
# # 删除df_final中有空值的列
# df_final_reduction = df_final_reduction.dropna(axis=1, how='any')
# df_final_reduction = clean_duplicates(df_final_reduction, ['Flowability'])
# # 检查df_f_cleaned和df_final_reduction是否一样
# df_f_cleaned = df_f_cleaned.dropna(subset=['Flowability'])
# df_f_cleaned = df_f_cleaned.dropna(axis=1, how='any')
# # 检查df_f_cleaned和df_final_reduction是否一样
# # df_f_cleaned.astype(float).compare(df_final_reduction.astype(float), keep_shape=True, keep_equal=True)
# df_f_cleaned.astype(float).equals(df_final_reduction.astype(float))

False

In [1]:
import pandas as pd
import os
from sklearn.model_selection import train_test_split

def clean_duplicates(df: pd.DataFrame, label_col_list: list) -> pd.DataFrame:
    """
    清理重复行，保留每组重复行的第一行，并计算其他行的平均值。

    :param df: 输入的DataFrame
    :param label_col_list: 用于分组的列名列表
    :return: 清理后的DataFrame
    """

    agg_dict = {col: 'mean' for col in label_col_list}
    cols_list = list(df.columns.difference(label_col_list))
    df_merged = (
        df
        .groupby(cols_list, dropna=False, sort=False)  # 若有缺失值也能一起分组
        .agg(agg_dict)
        .reset_index()
    )

    return df_merged

def combine_dataframes(df1: pd.DataFrame, df2: pd.DataFrame) -> pd.DataFrame:
    """
    合并两个DataFrame，保留所有样本。

    :param df1: 第一个DataFrame
    :param df2: 第二个DataFrame
    :param on: 用于合并的列名列表
    :param how: 合并方式，默认为'outer'
    :return: 合并后的DataFrame
    """
    cols_list = list(df1.columns.intersection(df2.columns))
    df_final = pd.merge(
        df1,
        df2,
        on=cols_list,
        how='outer',          # outer → 保留所有样本
    )
    return df_final


class DataSet_uhpc:
    """
    DataSet 类：
    1. 从给定路径加载数据（支持 .xlsx, .csv）
    2. 拆分特征和标签
    3. 返回测试集和训练集
    """
    def __init__(self, path, num_feature, test_size=0.2, seed=42, task_name=None):
        """
        :param path:        数据文件路径
        :param num_feature: 特征的数量
        :param test_size:   测试集的比例
        :param seed:        随机种子
        """
        # 合并path 和 UHPC_original.xlsx
        self.folder_path = path
        self.file_path = os.path.join(path, 'UHPC_original.xlsx')
        self.task_name = task_name
        self.tasks = {
            'Flowability': 21,
            'Porosity': 22,
            'Compressive strength': 24,
            'Flexural strength': 24
        }
        if self.task_name not in list(self.tasks.keys()):
            raise ValueError(f"Task name must be provided. Available tasks: {list(self.tasks.keys())}")
        self.num_feature = None
        self.test_size = test_size
        self.seed = seed



        # 从文件中读入 pandas.DataFrame
        self._load_raw()

        # 拆分训练集和测试集
        self._split_train_test()

        # 拆分特征和标签
        self._split_feature_label()

    def _load_raw(self):
        """
        根据扩展名自动选择读取方式
        :return: 读取到的数据集
        """

        self.df_f = pd.read_excel(self.file_path, sheet_name=list(self.tasks.keys())[0]).astype(float)
        self.df_p = pd.read_excel(self.file_path, sheet_name=list(self.tasks.keys())[1]).astype(float)
        self.df_cs = pd.read_excel(self.file_path, sheet_name=list(self.tasks.keys())[2]).astype(float)
        self.df_fs = pd.read_excel(self.file_path, sheet_name=list(self.tasks.keys())[3]).astype(float)

        self.df_f_cleaned = clean_duplicates(self.df_f, [list(self.tasks.keys())[0]])
        self.df_p_cleaned = clean_duplicates(self.df_p, [list(self.tasks.keys())[1]])
        self.df_cs_cleaned = clean_duplicates(self.df_cs, [list(self.tasks.keys())[2]])
        self.df_fs_cleaned = clean_duplicates(self.df_fs, [list(self.tasks.keys())[3]])

        self.columns = list(self.df_cs_cleaned.columns.intersection(self.df_fs_cleaned.columns)) + list(self.tasks.keys())

    def _split_train_test(self):
        """
        获取训练集的特征和标签
        :param task_name: 任务名称
        :return: 训练集特征和标签
        """

        self.num_feature = self.tasks[self.task_name]

        if self.task_name == 'Flowability':
            self.df_f_cleaned, self.test_df = train_test_split(self.df_f_cleaned, test_size=self.test_size,
                                                     random_state=self.seed)
        elif self.task_name == 'Porosity':
            self.df_p_cleaned, self.test_df = train_test_split(self.df_p_cleaned, test_size=self.test_size,
                                                     random_state=self.seed)
        elif self.task_name == 'Compressive strength':
            self.df_cs_cleaned, self.test_df = train_test_split(self.df_cs_cleaned, test_size=self.test_size,
                                                       random_state=self.seed)
        elif self.task_name == 'Flexural strength':
            self.df_fs_cleaned, self.test_df = train_test_split(self.df_fs_cleaned, test_size=self.test_size,
                                                       random_state=self.seed)

        self.train_df = combine_dataframes(combine_dataframes(combine_dataframes(self.df_f_cleaned, self.df_p_cleaned),
                                                         self.df_cs_cleaned), self.df_fs_cleaned)

        self.train_df = self.train_df[self.columns]

    def _split_feature_label(self):

        self.X_train = self.train_df.iloc[:, :self.num_feature].reset_index(drop=True)
        self.y_train = self.train_df.iloc[:, self.num_feature:].reset_index(drop=True)

        self.X_test = self.test_df.iloc[:, :self.num_feature].reset_index(drop=True)
        self.y_test = self.test_df.iloc[:, self.num_feature:].reset_index(drop=True)

    def get_train(self, split=True):
        if split:
            return self.X_train.copy(), self.y_train.copy()
        else:
            return self.train_df.copy()

    def get_test(self, split=True):
        if split:
            return self.X_test.copy(), self.y_test.copy()
        else:
            return self.test_df.copy()


    def get_name(self):

        return self.task_name

In [2]:
dataset = DataSet_uhpc(path='./', num_feature=24, task_name='Compressive strength')

In [3]:
df_final = dataset.get_train(split=False)
df_final

,1,2,3,4,5,6,7,8,9,10,...,19,20,21,22,23,24,Flowability,Porosity,Compressive strength,Flexural strength
0,582.1,52.5,1.0,0.0,259.9,0.0,0.0,24.3,0.0,1256.1,...,0.0,0.0,0.0,28.0,40.0,160.0,6.288737,12.88,100.07,12.752294
1,582.1,52.5,1.0,0.0,259.9,0.0,0.0,24.3,0.0,1256.1,...,0.0,0.0,0.0,91.0,40.0,160.0,6.288737,11.75,108.78,14.220183
2,591.9,52.5,1.0,0.0,264.3,0.0,0.0,24.7,0.0,1277.2,...,0.0,0.0,0.0,28.0,40.0,160.0,8.947639,12.06,105.43,14.495413
3,591.9,52.5,1.0,0.0,264.3,0.0,0.0,24.7,0.0,1277.2,...,0.0,0.0,0.0,91.0,NaN,NaN,8.947639,10.48,NaN,NaN
4,600.0,52.5,1.0,0.0,267.9,0.0,0.0,25.0,0.0,1294.6,...,0.0,0.0,0.0,28.0,NaN,NaN,11.264783,12.29,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,475.0,42.5,1.0,1.0,0.0,317.0,264.0,0.0,0.0,1056.0,...,2.0,0.2,13.0,91.0,40.0,160.0,NaN,NaN,NaN,41.496909
741,317.0,42.5,1.0,1.0,0.0,475.0,264.0,0.0,0.0,1056.0,...,2.0,0.2,13.0,91.0,40.0,160.0,NaN,NaN,NaN,34.259079
742,634.0,42.5,1.0,1.0,159.0,0.0,264.0,0.0,0.0,1056.0,...,2.0,0.2,13.0,91.0,40.0,160.0,NaN,NaN,NaN,38.504096
743,475.0,42.5,1.0,1.0,317.0,0.0,264.0,0.0,0.0,1056.0,...,2.0,0.2,13.0,91.0,40.0,160.0,NaN,NaN,NaN,34.714269
744,317.0,42.5,1.0,1.0,475.0,0.0,264.0,0.0,0.0,1056.0,...,2.0,0.2,13.0,91.0,40.0,160.0,NaN,NaN,NaN,32.354542

In [4]:
df_final = df_final.dropna(subset=['Compressive strength'])
# 删除df_final中有空值的列
df_final = df_final.dropna(axis=1, how='any')
df_final = clean_duplicates(df_final, ['Compressive strength'])
df_final

,1,2,3,4,5,6,7,8,9,10,...,16,17,18,19,20,21,22,23,24,Compressive strength
0,582.1,52.5,1.0,0.0,259.9,0.0,0.0,24.3,0.0,1256.1,...,0.0,0.0,0.0,0.0,0.0,0.0,28.0,40.0,160.0,100.07
1,582.1,52.5,1.0,0.0,259.9,0.0,0.0,24.3,0.0,1256.1,...,0.0,0.0,0.0,0.0,0.0,0.0,91.0,40.0,160.0,108.78
2,591.9,52.5,1.0,0.0,264.3,0.0,0.0,24.7,0.0,1277.2,...,0.0,0.0,0.0,0.0,0.0,0.0,28.0,40.0,160.0,105.43
3,596.1,52.5,1.0,0.0,0.0,266.1,0.0,24.8,0.0,1286.3,...,0.0,0.0,0.0,0.0,0.0,0.0,28.0,40.0,160.0,106.87
4,596.1,52.5,1.0,0.0,0.0,266.1,0.0,24.8,0.0,1286.3,...,0.0,0.0,0.0,0.0,0.0,0.0,91.0,40.0,160.0,117.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,720.0,42.5,1.0,0.0,0.0,0.0,80.0,0.0,0.0,1422.9,...,0.0,0.0,0.0,0.0,0.0,0.0,28.0,50.0,50.0,120.99
482,921.5,52.5,1.0,0.0,0.0,0.0,255.0,28.5,0.0,873.0,...,0.0,0.0,0.0,2.5,0.2,13.0,7.0,40.0,40.0,118.00
483,809.0,42.5,1.0,1.0,0.0,0.0,270.0,0.0,0.0,1000.0,...,0.0,0.0,0.0,2.0,0.2,13.0,1.0,40.0,160.0,67.65
484,776.0,42.5,1.0,0.0,0.0,0.0,0.0,24.0,0.0,1409.7,...,0.0,0.0,0.0,0.0,0.0,0.0,28.0,50.0,50.0,114.04
485,472.0,42.5,1.0,1.0,0.0,315.0,262.0,0.0,0.0,1049.0,...,0.0,0.0,0.0,2.0,0.2,13.0,28.0,40.0,160.0,122.00

In [5]:
df_final_test = dataset.get_test(split=False)

In [6]:
df_final_test

,1,2,3,4,5,6,7,8,9,10,...,16,17,18,19,20,21,22,23,24,Compressive strength
109,941.5,52.5,1.0,0.0,0.0,0.0,255.0,9.5,0.0,873.00,...,0.0,0.0,0.0,2.5,0.20,13.0,28.0,40.0,40.0,139.00
10,591.9,52.5,1.0,0.0,264.3,0.0,0.0,24.7,0.0,1277.20,...,0.0,0.0,0.0,0.0,0.00,0.0,91.0,40.0,160.0,116.07
184,657.0,52.5,1.0,1.0,0.0,429.8,119.4,0.0,0.0,1050.00,...,0.0,0.0,0.0,2.0,0.20,13.0,91.0,50.0,50.0,139.00
77,792.0,42.5,1.0,1.0,0.0,0.0,264.0,0.0,0.0,1056.00,...,0.0,0.0,0.0,2.0,0.20,13.0,3.0,40.0,160.0,103.90
538,630.0,52.5,1.0,1.0,0.0,0.0,70.0,0.0,0.0,622.05,...,0.0,0.0,0.0,0.0,0.00,0.0,56.0,100.0,100.0,146.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,670.5,52.5,1.0,1.0,0.0,0.0,74.5,0.0,0.0,500.00,...,1.5,25.0,12.0,0.0,0.00,0.0,730.0,100.0,100.0,158.52
165,594.2,52.5,1.0,0.0,0.0,0.0,0.0,24.8,265.3,1282.30,...,0.0,0.0,0.0,2.0,0.16,6.0,28.0,40.0,160.0,120.75
158,594.2,52.5,1.0,0.0,0.0,0.0,0.0,24.8,265.3,1282.30,...,0.0,0.0,0.0,2.0,0.17,7.0,7.0,40.0,160.0,112.63
543,450.0,52.5,1.0,1.0,0.0,0.0,50.0,0.0,0.0,693.39,...,0.0,0.0,0.0,0.0,0.00,0.0,180.0,100.0,100.0,158.48
176,606.4,52.5,1.0,0.0,0.0,270.7,25.3,0.0,0.0,1308.50,...,0.0,0.0,0.0,0.0,0.00,0.0,91.0,40.0,160.0,118.39